spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: rpg-character-sheet
  
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  
  web:
    resources:
      static-locations[0]: "file:src/main/resources/static/"
      static-locations[1]: "classpath:/static/"
      #cache-period: 0

  profiles:
    active: dev
